In [2]:
import pandas as pd

print(pd.__version__)

3.0.0

In [3]:
grades = pd.Series({"Anna": 15, "Nikos": 20, "Kostas": 18})
grades

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [4]:
grades.iloc[1]
grades.loc["Nikos"]

np.int64(20)

In [5]:
grades.iloc[:2]

Anna     15
Nikos    20
dtype: int64

# Math on Series

In [7]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([1, 2, 3])

# Scalar operations
s1 + 5
print(s1 * 10)

0    100
1    200
2    300
dtype: int64

In [8]:
# Vector Operations
s1 + s2

0    11
1    22
2    33
dtype: int64

In [9]:
grades1 = pd.Series({"Maria": 15, "Nikos": 20, "Kostas": 18})
grades + grades1

Anna       NaN
Kostas    36.0
Maria      NaN
Nikos     40.0
dtype: float64

# Series most useful functions

In [10]:
s1

0    10
1    20
2    30
dtype: int64

In [11]:
s1.sum()

np.int64(60)

In [12]:
s1.min()

np.int64(10)

In [14]:
s1.max()

np.int64(30)

In [15]:
s1.mean()

np.float64(20.0)

In [16]:
s1.sum()/len(s1)

np.float64(20.0)

In [18]:
s1.sort_values(ascending=False)

2    30
1    20
0    10
dtype: int64

In [19]:
s1.unique()

array([10, 20, 30])

In [20]:
s3 = pd.Series([10, 10, 20])
s3.value_counts()

10    2
20    1
Name: count, dtype: int64

In [21]:
grades

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [25]:
grades.max()

np.int64(20)

In [22]:
grades.idxmax()

'Nikos'

In [23]:
grades.nunique()

3

In [24]:
len(grades.unique())

3

In [ ]:
# Boolean Mask
grades
boolean_mas = pd.Series([True, False, True])

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [31]:
grades.isin([15, 20])

Anna       True
Nikos      True
Kostas    False
dtype: bool

In [ ]:
grades[]

Anna     15
Nikos    20
dtype: int64

In [33]:
grades > 16

Anna      False
Nikos      True
Kostas     True
dtype: bool

In [41]:
grades

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [42]:
grades[~grades.isin([20])]

Anna      15
Kostas    18
dtype: int64

In [44]:
score = pd.Series(0, ["Kostas", "Anna", 'Mitsos'], name="scores")
score

Kostas    0
Anna      0
Mitsos    0
Name: scores, dtype: int64

In [45]:
grades

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [47]:
def pow(x):
    return x**2

grades.map(pow)

Anna      225
Nikos     400
Kostas    324
dtype: int64

In [49]:
grades

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [ ]:
grades.map()

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [ ]:
# lambda parameters: return_values

In [52]:
grades.map(lambda x: x**2)

Anna      225
Nikos     400
Kostas    324
dtype: int64

In [53]:
grades

Anna      15
Nikos     20
Kostas    18
dtype: int64

In [54]:
grades.map({15: 16, 20:21, 18:19})

Anna      16
Nikos     21
Kostas    19
dtype: int64

In [55]:
class Series:
    def __init__(self, data):
        self.data = data
        self.dtype = type(data[0])

s = Series([1, 2, 3, 4])

In [56]:
s.dtype

int

In [ ]:
s = pd.Series()

In [57]:
data = {
    "Department": ["Sales", "Sales", "HR", "HR", "IT", "IT"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Salary": [50000, 60000, 45000, 48000, 70000, 72000]
}

df = pd.DataFrame(data)

In [58]:
df

  Department Employee  Salary
0      Sales    Alice   50000
1      Sales      Bob   60000
2         HR  Charlie   45000
3         HR    David   48000
4         IT      Eva   70000
5         IT    Frank   72000

In [59]:
df.columns = ["D", 'E', 'S']
df

       D        E      S
0  Sales    Alice  50000
1  Sales      Bob  60000
2     HR  Charlie  45000
3     HR    David  48000
4     IT      Eva  70000
5     IT    Frank  72000

In [61]:
data = {
    "Name": ["Alice", "Bob", "Carol", "David", "Eva"],
    "City": ["NY", "Paris", "NY", "Paris", "NY"],
    "Score": [85, 90, 95, 80, 70]
}

df = pd.DataFrame(data)
df

    Name   City  Score
0  Alice     NY     85
1    Bob  Paris     90
2  Carol     NY     95
3  David  Paris     80
4    Eva     NY     70