In [15]:
import pandas as pd

Άσκηση 1

In [32]:
customers = pd.read_csv("data/customers.csv")
orders = pd.read_csv("data/orders.csv")
employees = pd.read_csv("data/employees.csv")
orderdetails = pd.read_csv("data/orderdetails.csv")
products = pd.read_csv("data/products.csv", index_col="ProductID")
categories = pd.read_csv("data/categories.csv")
suppliers = pd.read_csv("data/suppliers.csv")
shippers = pd.read_csv("data/shippers.csv")

In [33]:
dfs = {
    "customers": customers,
    "orders": orders,
    "employees": employees,
    "orderdetails": orderdetails,
    "products": products,
    "categories": categories,
    "suppliers": suppliers,
    "shippers": shippers
}

Άσκηση 2

In [18]:
for name, df in dfs.items():
    print(f"Table {name} has shape {df.shape}")

Table customers has shape (91, 14)
Table orders has shape (830, 14)
Table employees has shape (9, 18)
Table orderdetails has shape (2155, 5)
Table products has shape (77, 10)
Table categories has shape (8, 4)
Table suppliers has shape (29, 12)
Table shippers has shape (3, 3)

Άσκηση 4

In [19]:
dfs["employees"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EmployeeID       9 non-null      int64
 1   LastName         9 non-null      object
 2   FirstName        9 non-null      object
 3   Title            9 non-null      object
 4   TitleOfCourtesy  9 non-null      object
 5   BirthDate        9 non-null      object
 6   HireDate         9 non-null      object
 7   Salary           9 non-null      int64
 8   Address          9 non-null      object
 9   City             9 non-null      object
 10  Region           5 non-null      object
 11  PostalCode       9 non-null      object
 12  Country          9 non-null      object
 13  HomePhone        9 non-null      object
 14  Extension        9 non-null      int64
 15  Photo            9 non-null      object
 16  Notes            9 non-null      object
 17  ReportsTo        8 non-null      float64
dtypes: float64(1), int64(3), object(14)
memory usage: 1.4+ KB

In [20]:
dfs["employees"].dtypes

EmployeeID           int64
LastName            object
FirstName           object
Title               object
TitleOfCourtesy     object
BirthDate           object
HireDate            object
Salary               int64
Address             object
City                object
Region              object
PostalCode          object
Country             object
HomePhone           object
Extension            int64
Photo               object
Notes               object
ReportsTo          float64
dtype: object

Άσκηση 5

In [25]:
dfs["customers"].isna().sum()

CustomerID         0
CompanyName        0
CustomerName       0
ContactTitle       0
Address            0
City               0
Region            60
PostalCode         1
Country            0
Phone              0
Fax               22
Image             91
ImageThumbnail    91
age               91
dtype: int64

In [26]:
# Drop
dfs["customers"].drop(["Image", "ImageThumbnail", "age"], axis=1, inplace=True)

In [27]:
dfs["customers"].isna().sum()

CustomerID       0
CompanyName      0
CustomerName     0
ContactTitle     0
Address          0
City             0
Region          60
PostalCode       1
Country          0
Phone            0
Fax             22
dtype: int64

Άσκηση 6

In [30]:
dfs["customers"].Country.nunique()

21

Άσκηση 7

In [35]:
dfs["products"][["ProductName", "Price"]]

                               ProductName  Price
ProductID
1                                     Chai  18.00
2                                    Chang  19.00
3                            Aniseed Syrup  10.00
4             Chef Anton's Cajun Seasoning  22.00
5                   Chef Anton's Gumbo Mix  21.35
...                                    ...    ...
73                              Röd Kaviar  15.00
74                           Longlife Tofu  10.00
75                    Rhönbräu Klosterbier   7.75
76                            Lakkalikööri  18.00
77         Original Frankfurter grüne Soße  13.00

[77 rows x 2 columns]

In [39]:
customers[["CompanyName", "Country", "City"]].iloc[[0, 3, 5]]

               CompanyName  Country      City
0      Alfreds Futterkiste  Germany    Berlin
3          Around the Horn       UK    London
5  Blauer See Delikatessen  Germany  Mannheim

In [44]:
orders.iloc[:4, :6]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate
0,10248,VINET,5,1994-08-04 00:00:00,1994-09-01 00:00:00,1994-08-16 00:00:00
1,10249,TOMSP,6,1994-08-05 00:00:00,1994-09-16 00:00:00,1994-08-10 00:00:00
2,10250,HANAR,4,1994-08-08 00:00:00,1994-09-05 00:00:00,1994-08-12 00:00:00
3,10251,VICTE,3,1994-08-08 00:00:00,1994-09-05 00:00:00,1994-08-15 00:00:00

In [48]:
customers[(customers.Country == "Germany") | (customers.Country == "France")]

,CustomerID,CompanyName,CustomerName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,Image,ImageThumbnail,age
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,NaN,12209,Germany,030-0074321,030-0076545,NaN,NaN,NaN
5,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,NaN,68306,Germany,0621-08460,0621-08924,NaN,NaN,NaN
6,BLONP,Blondel père et fils,Frédérique Citeaux,Marketing Manager,"24, place Kléber",Strasbourg,NaN,67000,France,88.60.15.31,88.60.15.32,NaN,NaN,NaN
8,BONAP,Bon app,Laurence Lebihan,Owner,"12, rue des Bouchers",Marseille,NaN,13008,France,91.24.45.40,91.24.45.41,NaN,NaN,NaN
16,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,NaN,52066,Germany,0241-039123,0241-059428,NaN,NaN,NaN
17,DUMON,Du monde entier,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,NaN,44000,France,40.67.88.88,40.67.89.89,NaN,NaN,NaN
22,FOLIG,Folies gourmandes,Martine Rancé,Assistant Sales Agent,"184, chaussée de Tournai",Lille,NaN,59000,France,20.16.10.16,20.16.10.17,NaN,NaN,NaN
24,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,München,NaN,80805,Germany,089-0877310,089-0877451,NaN,NaN,NaN
25,FRANR,France restauration,Carine Schmitt,Marketing Manager,"54, rue Royale",Nantes,NaN,44000,France,40.32.21.21,40.32.21.20,NaN,NaN,NaN
38,KOENE,Königlich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,NaN,14776,Germany,0555-09876,NaN,NaN,NaN,NaN
39,LACOR,La corne d'abondance,Daniel Tonini,Sales Representative,"67, avenue de l'Europe",Versailles,NaN,78000,France,30.59.84.10,30.59.85.11,NaN,NaN,NaN
40,LAMAI,La maison d'Asie,Annette Roulet,Sales Manager,1 rue Alsace-Lorraine,Toulouse,NaN,31000,France,61.77.61.10,61.77.61.11,NaN,NaN,NaN
43,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,NaN,60528,Germany,069-0245984,069-0245874,NaN,NaN,NaN
51,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,NaN,04179,Germany,0342-023176,NaN,NaN,NaN,NaN
55,OTTIK,Ottilies Käseladen,Henriette Pfalzheim,Owner,Mehrheimerstr. 369,Köln,NaN,50739,Germany,0221-0644327,0221-0765721,NaN,NaN,NaN
56,PARIS,Paris spécialités,Marie Bertrand,Owner,"265, boulevard Charonne",Paris,NaN,75012,France,(1) 42.34.22.66,(1) 42.34.22.77,NaN,NaN,NaN
62,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstraße 10,Cunewalde,NaN,01307,Germany,0372-035188,NaN,NaN,NaN,NaN
73,SPECD,Spécialités du monde,Dominique Perrier,Marketing Manager,"25, rue Lauriston",Paris,NaN,75016,France,(1) 47.55.60.10,(1) 47.55.60.20,NaN,NaN,NaN
78,TOMSP,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,NaN,44087,Germany,0251-031259,0251-035695,NaN,NaN,NaN
83,VICTE,Victuailles en stock,Mary Saveley,Sales Agent,"2, rue du Commerce",Lyon,NaN,69004,France,78.32.54.86,78.32.54.87,NaN,NaN,NaN
84,VINET,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,NaN,51100,France,26.47.15.10,26.47.15.11,NaN,NaN,NaN
85,WANDK,Die Wandernde Kuh,Rita Müller,Sales Representative,Adenauerallee 900,Stuttgart,NaN,70563,Germany,0711-020361,0711-035428,NaN,NaN,NaN

In [50]:
customers[customers.Country.isin(["Germany", "France", "Brazil"])]

,CustomerID,CompanyName,CustomerName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,Image,ImageThumbnail,age
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,NaN,12209,Germany,030-0074321,030-0076545,NaN,NaN,NaN
5,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,NaN,68306,Germany,0621-08460,0621-08924,NaN,NaN,NaN
6,BLONP,Blondel père et fils,Frédérique Citeaux,Marketing Manager,"24, place Kléber",Strasbourg,NaN,67000,France,88.60.15.31,88.60.15.32,NaN,NaN,NaN
8,BONAP,Bon app,Laurence Lebihan,Owner,"12, rue des Bouchers",Marseille,NaN,13008,France,91.24.45.40,91.24.45.41,NaN,NaN,NaN
14,COMMI,Comércio Mineiro,Pedro Afonso,Sales Associate,"Av. dos Lusíadas, 23",São Paulo,SP,05432-043,Brazil,(11) 555-7647,NaN,NaN,NaN,NaN
16,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,NaN,52066,Germany,0241-039123,0241-059428,NaN,NaN,NaN
17,DUMON,Du monde entier,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,NaN,44000,France,40.67.88.88,40.67.89.89,NaN,NaN,NaN
20,FAMIA,Familia Arquibaldo,Aria Cruz,Marketing Assistant,"Rua Orós, 92",São Paulo,SP,05442-030,Brazil,(11) 555-9857,NaN,NaN,NaN,NaN
22,FOLIG,Folies gourmandes,Martine Rancé,Assistant Sales Agent,"184, chaussée de Tournai",Lille,NaN,59000,France,20.16.10.16,20.16.10.17,NaN,NaN,NaN
24,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,München,NaN,80805,Germany,089-0877310,089-0877451,NaN,NaN,NaN
25,FRANR,France restauration,Carine Schmitt,Marketing Manager,"54, rue Royale",Nantes,NaN,44000,France,40.32.21.21,40.32.21.20,NaN,NaN,NaN
30,GOURL,Gourmet Lanchonetes,André Fonseca,Sales Associate,"Av. Brasil, 442",Campinas,SP,04876-786,Brazil,(11) 555-9482,NaN,NaN,NaN,NaN
33,HANAR,Hanari Carnes,Mario Pontes,Accounting Manager,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil,(21) 555-0091,(21) 555-8765,NaN,NaN,NaN
38,KOENE,Königlich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,NaN,14776,Germany,0555-09876,NaN,NaN,NaN,NaN
39,LACOR,La corne d'abondance,Daniel Tonini,Sales Representative,"67, avenue de l'Europe",Versailles,NaN,78000,France,30.59.84.10,30.59.85.11,NaN,NaN,NaN
40,LAMAI,La maison d'Asie,Annette Roulet,Sales Manager,1 rue Alsace-Lorraine,Toulouse,NaN,31000,France,61.77.61.10,61.77.61.11,NaN,NaN,NaN
43,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,NaN,60528,Germany,069-0245984,069-0245874,NaN,NaN,NaN
51,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,NaN,04179,Germany,0342-023176,NaN,NaN,NaN,NaN
55,OTTIK,Ottilies Käseladen,Henriette Pfalzheim,Owner,Mehrheimerstr. 369,Köln,NaN,50739,Germany,0221-0644327,0221-0765721,NaN,NaN,NaN
56,PARIS,Paris spécialités,Marie Bertrand,Owner,"265, boulevard Charonne",Paris,NaN,75012,France,(1) 42.34.22.66,(1) 42.34.22.77,NaN,NaN,NaN
60,QUEDE,Que Delícia,Bernardo Batista,Accounting Manager,"Rua da Panificadora, 12",Rio de Janeiro,RJ,02389-673,Brazil,(21) 555-4252,(21) 555-4545,NaN,NaN,NaN
61,QUEEN,Queen Cozinha,Lúcia Carvalho,Marketing Assistant,"Alameda dos Canàrios, 891",São Paulo,SP,05487-020,Brazil,(11) 555-1189,NaN,NaN,NaN,NaN
62,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstraße 10,Cunewalde,NaN,01307,Germany,0372-035188,NaN,NaN,NaN,NaN
66,RICAR,Ricardo Adocicados,Janete Limeira,Assistant Sales Agent,"Av. Copacabana, 267",Rio de Janeiro,RJ,02389-890,Brazil,(21) 555-3412,NaN,NaN,NaN,NaN
73,SPECD,Spécialités du monde,Dominique Perrier,Marketing Manager,"25, rue Lauriston",Paris,NaN,75016,France,(1) 47.55.60.10,(1) 47.55.60.20,NaN,NaN,NaN
78,TOMSP,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,NaN,44087,Germany,0251-031259,0251-035695,NaN,NaN,NaN
80,TRADH,Tradição Hipermercados,Anabela Domingues,Sales Representative,"Av. Inês de Castro, 414",São Paulo,SP,05634-030,Brazil,(11) 555-2167,(11) 555-2168,NaN,NaN,NaN
83,VICTE,Victuailles en stock,Mary Saveley,Sales Agent,"2, rue du Commerce",Lyon,NaN,69004,France,78.32.54.86,78.32.54.87,NaN,NaN,NaN
84,VINET,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,NaN,51100,France,26.47.15.10,26.47.15.11,NaN,NaN,NaN
85,WANDK,Die Wandernde Kuh,Rita Müller,Sales Representative,Adenauerallee 900,Stuttgart,NaN,70563,Germany,0711-020361,0711-035428,NaN,NaN,NaN
87,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,SP,08737-363,Brazil,(14) 555-8122,NaN,NaN,NaN,NaN