In [72]:
import pandas as pd

customers = pd.read_csv('data/customers.csv', usecols=["CustomerID", 'CustomerName', 'City'], index_col="CustomerID", dtype={"City": str})
customers

                       CustomerName         City
CustomerID
ALFKI                  Maria Anders       Berlin
ANATR                  Ana Trujillo  México D.F.
ANTON                Antonio Moreno  México D.F.
AROUT                  Thomas Hardy       London
BERGS            Christina Berglund        Luleå
...                             ...          ...
WARTH              Pirkko Koskitalo         Oulu
WELLI                 Paula Parente      Resende
WHITC                Karl Jablonski      Seattle
WILMK               Matti Karttunen     Helsinki
WOLZA       Zbyszek Piestrzeniewicz     Warszawa

[91 rows x 2 columns]

In [73]:
customers.loc['ANTON']

CustomerName    Antonio Moreno
City               México D.F.
Name: ANTON, dtype: str

# Accessing Data

In [74]:
customers.head(10)

                  CustomerName         City
CustomerID
ALFKI             Maria Anders       Berlin
ANATR             Ana Trujillo  México D.F.
ANTON           Antonio Moreno  México D.F.
AROUT             Thomas Hardy       London
BERGS       Christina Berglund        Luleå
BLAUS               Hanna Moos     Mannheim
BLONP       Frédérique Citeaux   Strasbourg
BOLID            Martín Sommer       Madrid
BONAP         Laurence Lebihan    Marseille
BOTTM        Elizabeth Lincoln    Tsawassen

In [75]:
customers.tail()

                       CustomerName      City
CustomerID
WARTH              Pirkko Koskitalo      Oulu
WELLI                 Paula Parente   Resende
WHITC                Karl Jablonski   Seattle
WILMK               Matti Karttunen  Helsinki
WOLZA       Zbyszek Piestrzeniewicz  Warszawa

In [76]:
customers.info()

<class 'pandas.DataFrame'>
Index: 91 entries, ALFKI to WOLZA
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerName  91 non-null     str
 1   City          91 non-null     str
dtypes: str(2)
memory usage: 4.2+ KB

In [77]:
order_details = pd.read_csv('data/orderdetails.csv')
order_details.head()

   OrderID  ProductID  Price  Quantity  Discount
0    10248         11   14.0        12       0.0
1    10248         42    9.8        10       0.0
2    10248         72   34.8         5       0.0
3    10249         14   18.6         9       0.0
4    10249         51   42.4        40       0.0

In [78]:
order_details.info()

<class 'pandas.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    2155 non-null   int64
 1   ProductID  2155 non-null   int64
 2   Price      2155 non-null   float64
 3   Quantity   2155 non-null   int64
 4   Discount   2155 non-null   float64
dtypes: float64(2), int64(3)
memory usage: 84.3 KB

In [79]:
order_details.describe()

            OrderID    ProductID        Price     Quantity     Discount
count   2155.000000  2155.000000  2155.000000  2155.000000  2155.000000
mean   10659.375870    40.793039    26.218520    23.812993     0.056167
std      241.378032    22.159019    29.827418    19.022047     0.083450
min    10248.000000     1.000000     2.000000     1.000000     0.000000
25%    10451.000000    22.000000    12.000000    10.000000     0.000000
50%    10657.000000    41.000000    18.400000    20.000000     0.000000
75%    10862.500000    60.000000    32.000000    30.000000     0.100000
max    11077.000000    77.000000   263.500000   130.000000     0.250000

In [80]:
customers.describe()

        CustomerName    City
count             91      91
unique            91      69
top     Maria Anders  London
freq               1       6

In [81]:
customers.shape

(91, 2)

In [82]:
order_details.shape

(2155, 5)

# Selecting Rows/Columns

In [83]:
customers[["City"]]

                   City
CustomerID
ALFKI            Berlin
ANATR       México D.F.
ANTON       México D.F.
AROUT            London
BERGS             Luleå
...                 ...
WARTH              Oulu
WELLI           Resende
WHITC           Seattle
WILMK          Helsinki
WOLZA          Warszawa

[91 rows x 1 columns]

In [84]:
order_details[["Price"]]

      Price
0     14.00
1      9.80
2     34.80
3     18.60
4     42.40
...     ...
2150  33.25
2151  17.00
2152  15.00
2153   7.75
2154  13.00

[2155 rows x 1 columns]

In [85]:
order_details[["Price", "Discount"]]

      Price  Discount
0     14.00      0.00
1      9.80      0.00
2     34.80      0.00
3     18.60      0.00
4     42.40      0.00
...     ...       ...
2150  33.25      0.03
2151  17.00      0.00
2152  15.00      0.01
2153   7.75      0.00
2154  13.00      0.00

[2155 rows x 2 columns]

In [86]:
print(order_details.loc[1]["Price"])

9.8

In [87]:
order_details

      OrderID  ProductID  Price  Quantity  Discount
0       10248         11  14.00        12      0.00
1       10248         42   9.80        10      0.00
2       10248         72  34.80         5      0.00
3       10249         14  18.60         9      0.00
4       10249         51  42.40        40      0.00
...       ...        ...    ...       ...       ...
2150    11077         64  33.25         2      0.03
2151    11077         66  17.00         1      0.00
2152    11077         73  15.00         2      0.01
2153    11077         75   7.75         4      0.00
2154    11077         77  13.00         2      0.00

[2155 rows x 5 columns]

In [88]:
order_details["Total"] = order_details['Price'] * order_details["Quantity"] * (1 - order_details["Discount"])

In [89]:
order_details.head()

   OrderID  ProductID  Price  Quantity  Discount   Total
0    10248         11   14.0        12       0.0   168.0
1    10248         42    9.8        10       0.0    98.0
2    10248         72   34.8         5       0.0   174.0
3    10249         14   18.6         9       0.0   167.4
4    10249         51   42.4        40       0.0  1696.0

In [90]:
order_details.tail()

      OrderID  ProductID  Price  Quantity  Discount   Total
2150    11077         64  33.25         2      0.03  64.505
2151    11077         66  17.00         1      0.00  17.000
2152    11077         73  15.00         2      0.01  29.700
2153    11077         75   7.75         4      0.00  31.000
2154    11077         77  13.00         2      0.00  26.000

In [91]:
order_details.loc[len(order_details)] = {"OrderID": 11111, "ProductID": 74}

In [92]:
order_details.tail()

      OrderID  ProductID  Price  Quantity  Discount  Total
2151    11077         66  17.00       1.0      0.00   17.0
2152    11077         73  15.00       2.0      0.01   29.7
2153    11077         75   7.75       4.0      0.00   31.0
2154    11077         77  13.00       2.0      0.00   26.0
2155    11111         74    NaN       NaN       NaN    NaN

In [93]:
order_details.loc[2154, 'Quantity'] = 4

In [94]:
order_details.tail()

      OrderID  ProductID  Price  Quantity  Discount  Total
2151    11077         66  17.00       1.0      0.00   17.0
2152    11077         73  15.00       2.0      0.01   29.7
2153    11077         75   7.75       4.0      0.00   31.0
2154    11077         77  13.00       4.0      0.00   26.0
2155    11111         74    NaN       NaN       NaN    NaN

# Delete rows and columns

In [95]:
order_details.drop('Total', axis=1, inplace=True)
order_details

      OrderID  ProductID  Price  Quantity  Discount
0       10248         11  14.00      12.0      0.00
1       10248         42   9.80      10.0      0.00
2       10248         72  34.80       5.0      0.00
3       10249         14  18.60       9.0      0.00
4       10249         51  42.40      40.0      0.00
...       ...        ...    ...       ...       ...
2151    11077         66  17.00       1.0      0.00
2152    11077         73  15.00       2.0      0.01
2153    11077         75   7.75       4.0      0.00
2154    11077         77  13.00       4.0      0.00
2155    11111         74    NaN       NaN       NaN

[2156 rows x 5 columns]

In [96]:
order_details = order_details.drop(0)
order_details

      OrderID  ProductID  Price  Quantity  Discount
1       10248         42   9.80      10.0      0.00
2       10248         72  34.80       5.0      0.00
3       10249         14  18.60       9.0      0.00
4       10249         51  42.40      40.0      0.00
5       10250         41   7.70      10.0      0.00
...       ...        ...    ...       ...       ...
2151    11077         66  17.00       1.0      0.00
2152    11077         73  15.00       2.0      0.01
2153    11077         75   7.75       4.0      0.00
2154    11077         77  13.00       4.0      0.00
2155    11111         74    NaN       NaN       NaN

[2155 rows x 5 columns]

# Index Operations

In [97]:
products = pd.read_csv('data/products.csv')

In [98]:
products

,ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,Price,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0
1,2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
72,73,Röd Kaviar,17,8,24 - 150 g jars,15.00,101,0,5,0
73,74,Longlife Tofu,4,7,5 kg pkg.,10.00,4,20,5,0
74,75,Rhönbräu Klosterbier,12,1,24 - 0.5 l bottles,7.75,125,0,25,0
75,76,Lakkalikööri,23,1,500 ml,18.00,57,0,20,0
76,77,Original Frankfurter grüne Soße,12,2,12 boxes,13.00,32,0,15,0

In [99]:
products.set_index('ProductID')

,ProductName,SupplierID,CategoryID,QuantityPerUnit,Price,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
ProductID,,,,,,,,,
1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0
2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0
3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0
4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0
5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1
...,...,...,...,...,...,...,...,...,...
73,Röd Kaviar,17,8,24 - 150 g jars,15.00,101,0,5,0
74,Longlife Tofu,4,7,5 kg pkg.,10.00,4,20,5,0
75,Rhönbräu Klosterbier,12,1,24 - 0.5 l bottles,7.75,125,0,25,0
76,Lakkalikööri,23,1,500 ml,18.00,57,0,20,0
77,Original Frankfurter grüne Soße,12,2,12 boxes,13.00,32,0,15,0

In [100]:
products.rename(columns={'ProductName':'Name'})

,ProductID,Name,SupplierID,CategoryID,QuantityPerUnit,Price,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0
1,2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
72,73,Röd Kaviar,17,8,24 - 150 g jars,15.00,101,0,5,0
73,74,Longlife Tofu,4,7,5 kg pkg.,10.00,4,20,5,0
74,75,Rhönbräu Klosterbier,12,1,24 - 0.5 l bottles,7.75,125,0,25,0
75,76,Lakkalikööri,23,1,500 ml,18.00,57,0,20,0
76,77,Original Frankfurter grüne Soße,12,2,12 boxes,13.00,32,0,15,0