In [13]:
import pandas as pd

employee = pd.DataFrame({"Name": ["Alice", "Bob"]}, index=[1, 2])
employee

    Name
1  Alice
2    Bob

In [8]:
salary = pd.DataFrame({"Salary": [50_000, 60_000]}, index=[1, 2])
salary

   Salary
1   50000
2   60000

In [11]:
employee.join(salary, how="right")

    Name  Salary
1  Alice   50000
2    NaN   60000

In [14]:
employee.loc[3, "Name"] = "Alex"
employee

    Name
1  Alice
2    Bob
3   Alex

## Exercise 3

In [21]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104],
    "Name": ["Anna", "Nikos", "Maria", "John"],
    "Department": ["CS", "Math", "Physics", "CS"]
})

grades = pd.DataFrame({
    "id": [101, 102, 104, 105],
    "Score": [85, 90, 78, 88]
})

In [19]:
students_with_grades = students.merge(grades, left_on="student_id", right_on="id", how="left")
students_with_grades

   student_id   Name Department     id  Score
0         101   Anna         CS  101.0   85.0
1         102  Nikos       Math  102.0   90.0
2         103  Maria    Physics    NaN    NaN
3         104   John         CS  104.0   78.0

In [20]:
students_with_grades[students_with_grades["Score"].isna()]

   student_id   Name Department  id  Score
2         103  Maria    Physics NaN    NaN

In [24]:
students_with_grades["Score"] = students_with_grades["Score"].fillna(0)
students_with_grades

   student_id   Name Department     id  Score
0         101   Anna         CS  101.0   85.0
1         102  Nikos       Math  102.0   90.0
2         103  Maria    Physics    NaN    0.0
3         104   John         CS  104.0   78.0

In [26]:
students_with_grades["Passed"] = students_with_grades["Score"] >= 50
students_with_grades

   student_id   Name Department     id  Score  Passed
0         101   Anna         CS  101.0   85.0    True
1         102  Nikos       Math  102.0   90.0    True
2         103  Maria    Physics    NaN    0.0   False
3         104   John         CS  104.0   78.0    True

Άσκηση 3
Δίνονται:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104],
    "Name": ["Anna", "Nikos", "Maria", "John"],
    "Department": ["CS", "Math", "Physics", "CS"]
})

grades = pd.DataFrame({
    "id": [101, 102, 104, 105],
    "Score": [85, 90, 78, 88]
})
Ζητούνται:
1.	Να γίνει left merge ώστε να κρατηθούν όλοι οι φοιτητές.
2.	Να εντοπιστούν ποιοι φοιτητές δεν έχουν βαθμό.
3.	Να αντικατασταθούν οι ελλείπουσες τιμές της Score με 0.
4.	Να προστεθεί στήλη Passed που να είναι True αν Score >= 50, αλλιώς False.

In [ ]:
students_with_grades = students.merge(grades, left_on="student_id", right_on="id", how="left")
missing_grades = students_with_grades[students_with_grades["Score"].isna()]
students_with_grades["Score"] = students_with_grades["Score"].fillna(0)
students_with_grades["Passed"] = students_with_grades["Score"] >= 50

missing_grades, students_with_grades